version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: movie_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: movie_backend
    ports:
      - "5007:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/movie_booking
      - PORT=5000

  frontend:
    build: ./frontend
    container_name: movie_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
